version: "3"

services:
  spacecraftorigins:
    build: ./spacecraftOrigins
    # ports:
    #   - "8080:8080"
    environment:
      - CHALLENGE_ID='01582d9d-1021-43bd-b210-031fbe1ea1ab'
      - PUBLIC_IP=34.163.120.130
      - PUBLIC_ENDPOINT=spacecraftorigins
      - FLAG=shellmates{he4v3NLy_0RiG1n4Ted_Tr4N$$4ct1On}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: "1.0"
    
  stupidcontract:
    build: ./stupidContract
    # ports:
    #   - "8080:8080"
    environment:
      - CHALLENGE_ID='78c13866-8569-4ced-aca2-d9717c44a833'
      - PUBLIC_IP=34.163.120.130
      - PUBLIC_ENDPOINT=stupidcontract
      - FLAG=shellmates{y0u_S33_evm_0PC0d3s_4r3_L1KE_4S$$EmBly}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: "1.0"

  nginx:
    build: ./nginx
    ports:
    - 80:80
