version: "3"

services:
  prayvatevault:
    build: ./prayVateVault
    # ports:
    #   - "8080:8080"
    environment:
      - CHALLENGE_ID='4b0e299e-ff0c-4f9a-b567-eba7895687bc'
      - PUBLIC_IP=localhost
      - PUBLIC_ENDPOINT=prayvatevault
      - FLAG=shellmates{pr1v4CY?__0R_PR4Y_tH4t_THeY_w0n7_sEE?}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: "1.0"
    
  shellcoin:
    build: ./shellcoin
    # ports:
    #   - "8080:8080"
    environment:
      - CHALLENGE_ID='9180039a-4e22-4a44-8dd2-733e4fef684e'
      - PUBLIC_IP=localhost
      - PUBLIC_ENDPOINT=shellcoin
      - FLAG=shellmates{the_CONTrACT_1nheRiT3d__4nD_ThE_GR4nDSOn_d1D_n0t__th4T$$_1mProPer_acCes$$_c0nTRoL}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: "1.0"

  nginx:
    build: ./nginx
    ports:
    - 80:80
