version: "3"

services:
  launcher:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - CHALLENGE_ID=${CHALLENGE_ID}
      - PUBLIC_IP=${PUBLIC_HOST}
      - PUBLIC_ENDPOINT=${PUBLIC_ENDPOINT}
      - FLAG=${FLAG}
      - HTTP_PORT=8545
      - PROXY_PORT=8080
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: "1.0"
  nginx:
    build: ./nginx
    ports:
    - 80:80
